language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      env: C_COMPILER=gcc-7 CXX_COMPILER=g++-7
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-7
          - g++-7

    - os: linux
      compiler: clang

install:
  - git submodule -q update --init --recursive

before_script:
  - if [ -n "${C_COMPILER}" ]; then export CC="${C_COMPILER}"; fi
  - if [ -n "${CXX_COMPILER}" ]; then export CXX="${CXX_COMPILER}"; fi
  - ${CXX} --version
  - cmake --version
  - mkdir build
  - cd build

script:
  - cmake ..
  - make VERBOSE=1

notifications:
  email: false
